/**
 * Semantic RAG retrieval over precomputed documentary chunks.
 * Chunks generated by: node scripts/ingest-lumia-rag.mjs
 */

export type RagChunk = {
  id: string;
  doc_id: string;
  title: string;
  category: string;
  content: string;
  embedding: number[];
};

export type RagPack = {
  version: number;
  model: string;
  generated_at: string;
  chunks: RagChunk[];
};

function cosine(a: number[], b: number[]): number {
  let dot = 0;
  let na = 0;
  let nb = 0;
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  if (na === 0 || nb === 0) return 0;
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

export async function embedQuery(
  apiKey: string,
  model: string,
  text: string,
): Promise<number[]> {
  const res = await fetch('https://api.openai.com/v1/embeddings', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ model, input: text }),
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`embedQuery failed ${res.status}: ${err.slice(0, 200)}`);
  }
  const json = await res.json();
  return json.data[0].embedding as number[];
}

/** Similarité cosinus : <0.32 bruit, ~0.38+ usage court OK, ~0.45+ fort. 0.25 trop bas (hello→Partenaire). */
export const RAG_MIN_SCORE = 0.38;

export function retrieveByEmbedding(
  pack: RagPack,
  queryEmbedding: number[],
  limit = 6,
  minScore = RAG_MIN_SCORE,
): Array<RagChunk & { score: number }> {
  return pack.chunks
    .map((chunk) => ({
      ...chunk,
      score: cosine(queryEmbedding, chunk.embedding),
    }))
    .filter((row) => row.score >= minScore)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);
}

export function formatRagForPrompt(
  hits: Array<Pick<RagChunk, 'id' | 'title' | 'category' | 'content'> & { score?: number }>,
): string {
  if (!hits.length) {
    return 'Aucun extrait documentaire pertinent. Dis-le clairement et oriente vers Paramètres / support. N’invente rien.';
  }
  return hits
    .map(
      (h, i) =>
        `### Extrait ${i + 1} (${h.id} · ${h.category} · ${h.title})\n${h.content}`,
    )
    .join('\n\n');
}
